tab_spaces = 2
max_width = 160
array_width = 160
chain_width = 160
comment_width = 160
struct_lit_width = 160
single_line_if_else_max_width = 160
fn_call_width = 160
struct_variant_width = 160
attr_fn_like_width = 160